services:
  - type: web
    name: doan3m-hr-api
    runtime: node    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true
